POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imdhc3RvbiIsImlkIjoiNjBlZGY1NWUzOWRlMTYzODc0ZjA0MjkxIiwiaWF0IjoxNjI2MjA3NTkwfQ.hAM64PhQr1TmZkucp2bY2SJYaZwUNAhs9F-lsoP4zyI

{
    "title": "Third authorizated blog",
    "author":"Gastón",
    "url":"www.newblog1.com",
    "likes":24
}