POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Fourth blog",
    "author":"Jim",
    "url":"www.newblog4.com",
    "likes":1551
}

###

GET http://localhost:3003/api/blogs